version: '3'

services:
  Raneto:
    image: raneto-linux
    build:
      context: Raneto-Docker/
      dockerfile: Dockerfile
    ports: 
    - "3000:3000"
    volumes:
    - document_data:/data/content

  teamcity.documentreleasenotes.api:
    image: teamcity.documentreleasenotes.api
    build:
      context: .
      dockerfile: Teamcity.DocumentReleaseNotes.Api/Dockerfile
    ports:
    - "32700:80"
    volumes:
    - document_data:/app/Documents
    - log_data:/app/Logs
    
  teamcity.documentreleasenotes.app:
    image: teamcity.documentreleasenotes.app
    build:
      context: .
      dockerfile: Teamcity.DocumentReleaseNotes/Dockerfile
    volumes:
    - document_data:/app/Documents
    - log_data:/app/Logs

  cron.update.documents:
    image: cron-update-alpine
    build:
      context: Cron-Docker/
      dockerfile: Dockerfile
    depends_on:
    - teamcity.documentreleasenotes.api

volumes:
  document_data:
  log_data: